[platformio]
default_envs = esp32-wrover-devkitc-v4

[env]
platform = espressif32@6.7.0
framework = arduino
upload_speed = 921600
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BNO08x@1.2.7
    adafruit/Adafruit Unified Sensor@1.1.15
    adafruit/Adafruit BusIO@1.17.4

[env:esp32-wrover-devkitc-v4]
board = esp32dev
board_build.flash_mode = dio
board_build.partitions = default.csv

